---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.6
    box: chef-centos-6.6
    box_url:  https://atlas.hashicorp.com/jcalonsoh/boxes/chef-centos-6.6/versions/1.0.0/providers/virtualbox.box
    customize:
          memsize: 1024
          cpus: 2

suites:
  - name: default
    run_list:
      - recipe[base::default]
    attributes:
